runtime: python39
service: TSNE
entrypoint: gunicorn -b :$PORT tsne:server

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  GOOGLE_CLOUD_PROJECT: 'awesome-advice-420021'
