runtime: python39
entrypoint: gunicorn -b :$PORT tsne:server

env_variables:
  GOOGLE_CLOUD_PROJECT: "your-project-id"

instance_class: B8

# Using basic scaling instead of automatic scaling
basic_scaling:
  max_instances: 10
  idle_timeout: 10m

handlers:
- url: /.*
  script: auto
  secure: always
